import Image from "next/image";
import Link from "next/link";

import { PublicShell } from "@/components/PublicShell";
import { Icon } from "@/components/Icon";
import { ProductCard } from "@/components/ProductCard";
import { Callout } from "@/components/Callout";
import { getCategories, getProducts } from "@/lib/catalog";

export const metadata = {
  title: "Products | Dingsheng Energy Limited",
  description: "LPG filling plant, transport and distribution, autogas and industrial LPG equipment from Dingsheng Energy Limited.",
};
export const dynamic = "force-dynamic";

export default async function ProductsPage() {
  const [categories, products] = await Promise.all([getCategories(), getProducts()]);

  return <PublicShell>
    <section className="relative min-h-[440px] overflow-hidden bg-[#061f2d]">
      <Image src="/media/hero-products.jpg" alt="Dingsheng Energy LPG equipment" fill priority className="object-cover" />
      <div className="absolute inset-0 bg-gradient-to-r from-[#061f2d]/96 via-[#061f2d]/75 to-[#061f2d]/20" />
      <div className="container-shell relative z-10 flex min-h-[440px] items-center py-20"><div className="max-w-[720px]"><div className="flex items-center gap-3 text-xs font-black uppercase tracking-[.17em] text-[#48d49c]"><span className="h-[2px] w-8 bg-[#48d49c]"/>Premium LPG Equipment</div><h1 className="mt-4 text-[50px] font-black tracking-[-.04em] text-white md:text-[64px]">Our Products</h1><p className="mt-6 max-w-[650px] text-base leading-8 text-white/74">Integrated LPG equipment and components for storage, filling, transfer, transport, autogas refueling and industrial applications.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="#catalogue" className="btn btn-primary">Browse Catalogue →</Link><Link href="/contact#rfq" className="btn border border-white/35 text-white">Request Assistance</Link></div></div></div>
    </section>

    <div className="border-b border-[#e4ebe7] bg-white"><div className="container-shell flex min-h-[58px] items-center gap-2 text-xs font-semibold text-[#7a8c94]"><Link href="/" className="hover:text-[#0a9c63]">Home</Link><span>›</span><span className="text-[#18313d]">Products</span></div></div>

    <section className="section bg-white"><div className="container-shell"><div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div className="max-w-3xl"><div className="eyebrow">Product Categories</div><h2 className="h2 mt-3">Four Integrated LPG Product Systems</h2><p className="mt-4 text-sm leading-7 text-[#687b84]">Browse equipment by application so related storage, transfer, safety, instrumentation and operating equipment stay organized within the same system.</p></div><Link href="/dealer/login" className="btn btn-secondary">Dealer Login →</Link></div><div className="grid-4 mt-10">{categories.map((category,i)=><Link key={category.slug} href={`/products/${category.slug}`} className="group overflow-hidden rounded-xl border border-[#dfe8e4] bg-white shadow-sm transition hover:-translate-y-1 hover:shadow-xl"><div className="relative h-[210px] overflow-hidden"><Image src={category.image} alt={category.name} fill className="object-cover transition duration-500 group-hover:scale-[1.04]"/><div className="absolute inset-0 bg-gradient-to-t from-[#071f2c]/75 to-transparent"/><div className="absolute bottom-4 left-5 flex h-11 w-11 items-center justify-center rounded-full border-4 border-white bg-[#0a9c63] text-xs font-black text-white">0{i+1}</div></div><div className="p-6"><h3 className="text-xl font-black uppercase leading-tight">{category.name}</h3><p className="mt-3 min-h-[72px] text-sm leading-6 text-[#697d86]">{category.summary}</p><div className="mt-4 flex flex-wrap gap-2">{category.groups.slice(0,3).map((group)=><span key={group} className="rounded-full bg-[#edf8f2] px-2.5 py-1 text-[10px] font-bold text-[#16805b]">{group}</span>)}</div><div className="mt-6 text-xs font-extrabold text-[#0a9c63]">Explore products →</div></div></Link>)}</div></div></section>

    <section id="catalogue" className="section soft-section"><div className="container-shell"><div className="flex flex-wrap items-end justify-between gap-5"><div><div className="eyebrow">Equipment Catalogue</div><h2 className="h2 mt-3">Explore LPG Equipment</h2><p className="mt-3 max-w-2xl text-sm leading-7 text-[#687b84]">Technical product information is public. Commercial pricing remains protected for approved dealers.</p></div><div className="flex gap-3"><span className="pill">{products.length} products</span><Link href="/dealer/login" className="btn btn-primary">View Dealer Pricing →</Link></div></div><div className="mt-10 grid gap-7 lg:grid-cols-[245px_minmax(0,1fr)]"><aside className="self-start rounded-xl border border-[#dfe8e4] bg-white p-5 lg:sticky lg:top-24"><div className="text-xs font-black uppercase tracking-[.12em]">Browse Systems</div><div className="mt-4 grid gap-1">{categories.map((category)=><Link key={category.slug} href={`/products/${category.slug}`} className="flex items-center justify-between rounded-md px-3 py-3 text-xs font-bold text-[#536a75] hover:bg-[#edf7f2] hover:text-[#0a9c63]">{category.shortName || category.name}<span>›</span></Link>)}</div><div className="my-5 border-t border-[#e4ebe7]"/><div className="rounded-lg bg-[#fff8e7] p-4"><div className="flex items-center gap-2 text-xs font-black text-[#9a6900]"><Icon name="lock" className="h-4 w-4"/>Dealer Pricing</div><p className="mt-2 text-[11px] leading-5 text-[#81765d]">Approved dealers can access commercial pricing through the secure portal.</p></div><Link href="/dealer/apply" className="mt-4 flex h-10 items-center justify-center border border-[#0a9c63] text-[10px] font-extrabold uppercase tracking-wide text-[#0a9c63]">Apply for Dealer Access</Link></aside><div><div className="mb-5 flex items-center justify-between rounded-lg border border-[#dfe8e4] bg-white px-4 py-3 text-xs text-[#6c7f87]"><span>Showing active catalogue products</span><span className="inline-flex items-center gap-1 rounded-full bg-[#fff6db] px-3 py-1 text-[10px] font-black text-[#c58d00]"><Icon name="lock" className="h-3 w-3"/>Dealer Protected</span></div><div className="grid gap-5 sm:grid-cols-2 xl:grid-cols-3">{products.map((product)=><ProductCard key={product.slug} product={product}/>)}</div></div></div></div></section>

    <section className="section bg-white"><div className="container-shell"><div className="mx-auto max-w-3xl text-center"><div className="eyebrow">Complete Product Coverage</div><h2 className="h2 mt-3">Equipment Across the LPG Value Chain</h2></div><div className="mt-10 grid gap-5 md:grid-cols-2">{categories.map((category)=><div key={category.slug} className="rounded-xl border border-[#dee8e3] p-7"><h3 className="text-xl font-black">{category.name}</h3><div className="mt-5 grid gap-2 sm:grid-cols-2">{category.groups.map((group)=><div key={group} className="flex items-center gap-3 border-b border-[#edf1ef] py-2 text-xs font-semibold text-[#526b76]"><span className="h-1.5 w-1.5 rounded-full bg-[#0a9c63]"/>{group}</div>)}</div><Link href={`/products/${category.slug}`} className="mt-6 inline-flex text-xs font-extrabold uppercase tracking-wide text-[#0a9c63]">Explore category →</Link></div>)}</div></div></section>
    <section className="section-sm soft-section"><div className="container-shell"><Callout title="Can't Find the Equipment You Need?" copy="Tell our team about your application, technical requirements or LPG project and we can help identify the appropriate solution."/></div></section>
  </PublicShell>;
}
